### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [tranqhuy46/google-organic-search#7]
Hello Hui 👋 , thank you for your effort on the code submission. I am Olivier from Nimble and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us immediately so we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
I have now completed the first round of reviews. Have a check on the opened issue and share your feedback with us.

Note that we keep the code review limited, and I opened only the most prominent issues to keep the review process short and efficient. The goal is not to fix everything but to simulate how we could work together in a code review process.

**Comment by tranqhuy46** [comment]
Hi Oliver, I think I will focus on fixing bugs first, then I will do the testing part.

**Comment by olivierobert** [comment]
Hi Huy, I noticed you made two PRs to address the bugs. Thanks for your effort. However, I would like to get your feedback on the open issues. I am also interested in hearing back from you on each of them. Since we aim to keep the code review process short, we do not expect fixes for all open issues.

**Comment by olivierobert** [comment]
Hi Huy, 

I have reviewed the last two PRs and added one comment on one of them. 

Still, you have fallen short of our expectations as you have not replied or engaged in a discussion on any open issue. Unfortunately, it is now time to wrap up this stage of the recruitment process. I will take into account my observations in the code review process as part of my final assessment.

Thank you for your effort so far.
